### ISSUE TITLE
[Linux] Build fails

### ISSUE THREAD

**Issue by yochananmarqos** [timche/gmail-desktop#230]
- Gmail Desktop Version: 2.21.2
- OS Version: Manjaro GNOME

Building 2.21.0 is fine, but anything newer than that fails.

`package.json` modifications:
```
    "linux": {
      "target": [
        "dir"
      ],
```
```
    "dist:others": "electron-builder --linux --publish never"
```

```
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info dmg-license@1.0.8: The platform "linux" is incompatible with this module.
info "dmg-license@1.0.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info iconv-corefoundation@1.1.5: The platform "linux" is incompatible with this module.
info "iconv-corefoundation@1.1.5" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "xo > eslint-import-resolver-webpack@0.13.0" has unmet peer dependency "webpack@>=1.11.0".
[4/4] Building fresh packages...
$ electron-builder install-app-deps
  • electron-builder  version=22.10.5
  • loaded configuration  file=package.json ("build" field)
$ husky install
husky - not a Git repository, skipping hooks installation
Done in 21.88s.
yarn run v1.22.10
$ electron-builder --linux --publish never
  • electron-builder  version=22.10.5 os=5.11.5-1-MANJARO
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=12.0.0 appOutDir=dist/linux-unpacked
  • Unpacking electron zip  zipPath=undefined
  • downloading     url=https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip size=79 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip duration=6.488s
  ⨯ Application entry file "dist-js/app.js" in the "/build/gmail-desktop/src/gmail-desktop-2.21.2/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  stackTrace=
                                                                                                                                                                                               Error: Application entry file "dist-js/app.js" in the "/build/gmail-desktop/src/gmail-desktop-2.21.2/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
                                                                                                                                                                                                   at error (/build/gmail-desktop/src/gmail-desktop-2.21.2/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
                                                                                                                                                                                                   at checkFileInArchive (/build/gmail-desktop/src/gmail-desktop-2.21.2/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:33:11)
                                                                                                                                                                                                   at LinuxPackager.checkFileInPackage (/build/gmail-desktop/src/gmail-desktop-2.21.2/node_modules/app-builder-lib/src/platformPackager.ts:430:7)
                                                                                                                                                                                                   at LinuxPackager.sanityCheckPackage (/build/gmail-desktop/src/gmail-desktop-2.21.2/node_modules/app-builder-lib/src/platformPackager.ts:481:5)
                                                                                                                                                                                                   at LinuxPackager.doPack (/build/gmail-desktop/src/gmail-desktop-2.21.2/node_modules/app-builder-lib/src/platformPackager.ts:253:5)
                                                                                                                                                                                                   at LinuxPackager.pack (/build/gmail-desktop/src/gmail-desktop-2.21.2/node_modules/app-builder-lib/src/platformPackager.ts:115:5)
                                                                                                                                                                                                   at Packager.doBuild (/build/gmail-desktop/src/gmail-desktop-2.21.2/node_modules/app-builder-lib/src/packager.ts:434:9)
                                                                                                                                                                                                   at executeFinally (/build/gmail-desktop/src/gmail-desktop-2.21.2/node_modules/builder-util/src/promise.ts:12:14)
                                                                                                                                                                                                   at Packager._build (/build/gmail-desktop/src/gmail-desktop-2.21.2/node_modules/app-builder-lib/src/packager.ts:369:31)
                                                                                                                                                                                                   at Packager.build (/build/gmail-desktop/src/gmail-desktop-2.21.2/node_modules/app-builder-lib/src/packager.ts:333:12)
                                                                                                                                                                                                   at executeFinally (/build/gmail-desktop/src/gmail-desktop-2.21.2/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by timche** [comment]
You are missing `tsc` from the `"dist": "tsc && run-s dist:*"` command. Run `yarn tsc` before running `electron-builder --linux`

**Comment by yochananmarqos** [comment]
Thanks, that did it.
