### ISSUE TITLE
Auto updater not working

### ISSUE THREAD

**Issue by markypython** [timche/gmail-desktop#47]
Auto updater was added in #12, but I don't think it is working for Mac since I haven't gotten the new release yet.  I tried restarting the app several times to see if that would trigger it to update, but that doesn't seem to do anything.

@timche Can you explain how auto updater is supposed to work and if there is something I am doing wrong?  Seems like there should be a more intuitive process for updating.

**Comment by timche** [comment]
According to the [documentation](https://www.electron.build/auto-update) and [this example](https://github.com/iffy/electron-updater-example), it should work out of the box when releasing on GitHub and calling `autoUpdater.checkForUpdatesAndNotify()`. Let's see what the log says in the next versions.

**Comment by timche** [comment]
After launching v2.5.0, this is the log:

```
[2019-04-09 13:07:43.017] [info] Checking for update
[2019-04-09 13:07:45.013] [info] Update for version 2.5.0 is not available (latest version: 2.5.0, downgrade is disallowed).
```

It looks like that it should work, let's see when we have released a new version.

**Comment by markypython** [comment]
Behold the culprit:

```
[2019-04-09 20:00:22.126] [info] Checking for update
[2019-04-09 20:00:23.706] [info] Found version 2.5.2 (url: gmail-desktop-2.5.2-mac.zip, gmail-desktop-2.5.2.dmg)
[2019-04-09 20:00:23.707] [info] Downloading update from gmail-desktop-2.5.2-mac.zip, gmail-desktop-2.5.2.dmg
[2019-04-09 20:00:23.730] [info] No cached update info available
[2019-04-09 20:00:23.874] [error] Error: Error: Cannot download "https://github.com/timche/gmail-desktop/releases/download/v2.5.2/gmail-desktop-2.5.2-mac.zip", status 404: Not Found
    at ClientRequest.request.createRequest.response (/Applications/Gmail Desktop.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:247:26)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (/Applications/Gmail Desktop.app/Contents/Resources/electron.asar/browser/api/net.js:207:12)
    at URLRequest.emit (events.js:182:13)
From previous event:
    at ElectronHttpExecutor.download (/Applications/Gmail Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/electronHttpExecutor.ts:23:73)
    at Object.task (/Applications/Gmail Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:54:34)
    at /Applications/Gmail Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:610:25
From previous event:
    at MacUpdater.executeDownload (/Applications/Gmail Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:545:68)
    at MacUpdater.doDownloadUpdate (/Applications/Gmail Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:49:17)
    at MacUpdater.downloadUpdate (/Applications/Gmail Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:420:19)
    at /Applications/Gmail Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:383:49
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/Gmail Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at MacUpdater.checkForUpdates (/Applications/Gmail Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at Object.<anonymous> (/Applications/Gmail Desktop.app/Contents/Resources/app.asar/src/app.ts:31:15)
    at Object.<anonymous> (/Applications/Gmail Desktop.app/Contents/Resources/app.asar/dist-js/app.js:156:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Object.<anonymous> (/Applications/Gmail Desktop.app/Contents/Resources/electron.asar/browser/init.js:188:8)
    at Object.<anonymous> (/Applications/Gmail Desktop.app/Contents/Resources/electron.asar/browser/init.js:190:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)
```

**Comment by timche** [comment]
It's weird that the artifact name is `Gmail.Desktop-2.5.2-mac.zip` but it looks for `gmail-desktop-2.5.2-mac.zip`. The updater is looking into the `latest-mac.yml` file to determine the file to download. 

Looking into `latest-mac.yml` and comparing with [Caprine](https://github.com/sindresorhus/caprine/releases), ours is wrong, although Caprine's file also has a capital first letter. I can't find any configuration in Caprine's repository and I'm sure we are doing something wrong even when we could fix it with #55, but to me it doesn't feel right yet.

**Comment by markypython** [comment]
I'm guessing the reason why Caprine works is because they don't have a space in the file name where we do.  That would probably explain the period vs using a dash.

**Comment by timche** [comment]
It's not only that, but look at `Caprine-2.30.2-mac.zip`, the first letter is also written as capital letter. Our log is looking for everything in lowercase. You know what I mean?

**Comment by markypython** [comment]
Yes, but I am guessing that the issue is not the casing but instead the space.  GitHub urls are probably not case sensitive.

**Comment by timche** [comment]
It could be possible, on the other hand please look at [their `latest-mac.yml`](https://github.com/sindresorhus/caprine/releases/download/v2.30.2/latest-mac.yml) and [ours](https://github.com/timche/gmail-desktop/releases/download/v2.5.2/latest-mac.yml). The `url` is exactly how the artifacts are named for some reason.

**Comment by timche** [comment]
I've ran `yarn run dist` to see what the output is and actually it generates `Gmail Desktop.2.5.2-mac.zip`. Probably the dot will be added by GitHub or by Travis when uploading to GitHub releases.

**Comment by timche** [comment]
Okay, it's really caused by the space in `Gmail Desktop`. Now I've changed `productName` to `GmailDesktop` and the `latest-mac.yml` is generated with `GmailDesktop-2.5.2-mac.zip`. Kinda unexpected behaviour. I'm wondering how others are doing it.

**Comment by markypython** [comment]
Closed in #55

**Comment by markypython** [comment]
Looks like this is broken again.  See log below:

```
[2019-04-30 19:35:48.785] [info] Checking for update
[2019-04-30 19:35:50.975] [info] Found version 2.8.2 (url: gmail-desktop-2.8.2-mac.zip, gmail-desktop-2.8.2-mac.dmg)
[2019-04-30 19:35:50.976] [info] Downloading update from gmail-desktop-2.8.2-mac.zip, gmail-desktop-2.8.2-mac.dmg
[2019-04-30 19:35:50.992] [info] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: +MowUgnVHP4au6CF8SusDei5L13NTXMMiKBL0F2HvgDxefkANMClbDDuRMbYRpkxM9ED6Lp4A/bWtBBC7kN6Rg==, expected: lb6J2QZe1BaFsh14znaAEx7gJt+ow0ylUG+dtYxO87H2cTUm2uFJ5PE/faxuIbVRRjSWsWMSP1+9IFr7RjfZ+A==. Directory for cached update will be cleaned
[2019-04-30 19:35:58.762] [info] New version 2.8.2 has been downloaded to /Users/mark/Library/Application Support/Caches/gmail-desktop-updater/pending/gmail-desktop-2.8.2-mac.zip
[2019-04-30 19:35:58.813] [info] / requested
[2019-04-30 19:35:58.818] [info] /1556670958768-3230.zip requested
[2019-04-30 19:35:58.818] [info] /1556670958768-3230.zip requested by Squirrel.Mac, pipe /Users/mark/Library/Application Support/Caches/gmail-desktop-updater/pending/gmail-desktop-2.8.2-mac.zip
[2019-04-30 19:35:59.781] [warn] Error: Could not locate update bundle for io.cheung.gmail-desktop within file:///Users/mark/Library/Caches/io.cheung.gmail-desktop.ShipIt/update.xJMBXT3/
[2019-04-30 19:35:59.782] [error] Error: Error: Could not locate update bundle for io.cheung.gmail-desktop within file:///Users/mark/Library/Caches/io.cheung.gmail-desktop.ShipIt/update.xJMBXT3/
[2019-04-30 19:36:03.953] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/timche/gmail-desktop/releases/download/v2.8.2/gmail-desktop-2.8.2-mac.zip)
[2019-04-30 19:36:49.338] [info] Checking for update
[2019-04-30 19:36:50.860] [info] Found version 2.8.2 (url: gmail-desktop-2.8.2-mac.zip, gmail-desktop-2.8.2-mac.dmg)
[2019-04-30 19:36:50.861] [info] Downloading update from gmail-desktop-2.8.2-mac.zip, gmail-desktop-2.8.2-mac.dmg
[2019-04-30 19:36:51.142] [info] Update has already been downloaded to /Users/mark/Library/Application Support/Caches/gmail-desktop-updater/pending/gmail-desktop-2.8.2-mac.zip).
[2019-04-30 19:36:51.184] [info] / requested
[2019-04-30 19:36:51.192] [info] /1556671011144-1179.zip requested
[2019-04-30 19:36:51.192] [info] /1556671011144-1179.zip requested by Squirrel.Mac, pipe /Users/mark/Library/Application Support/Caches/gmail-desktop-updater/pending/gmail-desktop-2.8.2-mac.zip
[2019-04-30 19:36:52.376] [warn] Error: Could not locate update bundle for io.cheung.gmail-desktop within file:///Users/mark/Library/Caches/io.cheung.gmail-desktop.ShipIt/update.Jqw4cMU/
[2019-04-30 19:36:52.377] [error] Error: Error: Could not locate update bundle for io.cheung.gmail-desktop within file:///Users/mark/Library/Caches/io.cheung.gmail-desktop.ShipIt/update.Jqw4cMU/
[2019-04-30 19:36:56.360] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/timche/gmail-desktop/releases/download/v2.8.2/gmail-desktop-2.8.2-mac.zip)
```

**Comment by timche** [comment]
It looks like changing the app id broke it. We'll need to revert it until we have proper solution to change app id and app name.

**Comment by timche** [comment]
@markypython can you confirm it's working again?

**Comment by markypython** [comment]
Yes, it is working now.

**Comment by lmcarreiro** [comment]
@timche I'm having the same error when I changed the app id of my electron app (not related to gmail desktop).

What did you do to change the app id without issues when updating? Are you still using the same app id to avoid this update issue?
